FROM golang:1.8-alpine

WORKDIR /go/src/github.com/opencontrol/compliance-masonry

RUN apk add --no-cache bash gcc git musl-dev
RUN go get \
      github.com/kisielk/errcheck \
      github.com/Masterminds/glide

CMD go build && \
    errcheck && \
    ./circleci/coverage.sh
