// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// Certification is an autogenerated mock type for the Certification type
type Certification struct {
	mock.Mock
}

// GetControlKeysFor provides a mock function with given fields: standardKey
func (_m *Certification) GetControlKeysFor(standardKey string) []string {
	ret := _m.Called(standardKey)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(standardKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetKey provides a mock function with given fields:
func (_m *Certification) GetKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSortedStandards provides a mock function with given fields:
func (_m *Certification) GetSortedStandards() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
