package mocks

import common "github.com/opencontrol/compliance-masonry/lib/common"
import mock "github.com/stretchr/testify/mock"

// Control is an autogenerated mock type for the Control type
type Control struct {
	mock.Mock
}

// GetFamily provides a mock function with given fields:
func (_m *Control) GetFamily() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *Control) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetDescription provides a mock function with given fields:
func (_m *Control) GetDescription() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

var _ common.Control = (*Control)(nil)
