package mocks

import "github.com/opencontrol/compliance-masonry/lib/common"
import "github.com/stretchr/testify/mock"

// Certification is an autogenerated mock type for the Certification type
type Certification struct {
	mock.Mock
}

// GetKey provides a mock function with given fields:
func (_m *Certification) GetKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSortedStandards provides a mock function with given fields:
func (_m *Certification) GetSortedStandards() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetStandards provides a mock function with given fields:
func (_m *Certification) GetStandards() map[string]common.Standard {
	ret := _m.Called()

	var r0 map[string]common.Standard
	if rf, ok := ret.Get(0).(func() map[string]common.Standard); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]common.Standard)
		}
	}

	return r0
}
