package mocks

import common "github.com/opencontrol/compliance-masonry/lib/common"
import mock "github.com/stretchr/testify/mock"

// RemoteSource is an autogenerated mock type for the RemoteSource type
type RemoteSource struct {
	mock.Mock
}

// GetConfigFile provides a mock function with given fields:
func (_m *RemoteSource) GetConfigFile() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetRevision provides a mock function with given fields:
func (_m *RemoteSource) GetRevision() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetURL provides a mock function with given fields:
func (_m *RemoteSource) GetURL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetContextDir provides a mock function with given fields:
func (_m *RemoteSource) GetContextDir() string {
        ret := _m.Called()

        var r0 string
        if rf, ok := ret.Get(0).(func() string); ok {
                r0 = rf()
        } else {
                r0 = ret.Get(0).(string)
        }

        return r0
}

var _ common.RemoteSource = (*RemoteSource)(nil)
