package mocks

import common "github.com/opencontrol/compliance-masonry/lib/common"
import mock "github.com/stretchr/testify/mock"

// Satisfies is an autogenerated mock type for the Satisfies type
type Satisfies struct {
	mock.Mock
}

// GetControlKey provides a mock function with given fields:
func (_m *Satisfies) GetControlKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetControlOrigin provides a mock function with given fields:
func (_m *Satisfies) GetControlOrigin() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetControlOrigins provides a mock function with given fields:
func (_m *Satisfies) GetControlOrigins() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetCoveredBy provides a mock function with given fields:
func (_m *Satisfies) GetCoveredBy() common.CoveredByList {
	ret := _m.Called()

	var r0 common.CoveredByList
	if rf, ok := ret.Get(0).(func() common.CoveredByList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.CoveredByList)
		}
	}

	return r0
}

// GetImplementationStatus provides a mock function with given fields:
func (_m *Satisfies) GetImplementationStatus() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetImplementationStatuses provides a mock function with given fields:
func (_m *Satisfies) GetImplementationStatuses() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetNarratives provides a mock function with given fields:
func (_m *Satisfies) GetNarratives() []common.Section {
	ret := _m.Called()

	var r0 []common.Section
	if rf, ok := ret.Get(0).(func() []common.Section); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Section)
		}
	}

	return r0
}

// GetParameters provides a mock function with given fields:
func (_m *Satisfies) GetParameters() []common.Section {
	ret := _m.Called()

	var r0 []common.Section
	if rf, ok := ret.Get(0).(func() []common.Section); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Section)
		}
	}

	return r0
}

// GetStandardKey provides a mock function with given fields:
func (_m *Satisfies) GetStandardKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

var _ common.Satisfies = (*Satisfies)(nil)
